---
spring:
  cloud:
    config:
      server:
        git:   
          defaultLabel: main       
          uri: https://github.com/yensei/Microservices-with-spring-cloud-practices               
          searchPaths: ConfigData
server:
  port: 8001

# This controls which Actuator web endpoints are exposed.  
# Ordinarily, only /actuator/health and /actuator/info are exposed, 
# But we need to allow external parties to POST to /bus-refresh:    
management:
  endpoints:
    web:
      exposure:
        include: info,health,bus-refresh
  